### PR TITLE
Added filters to Walk method signature

### PR DESCRIPTION
**Pull request by Zyqsempai**
Signed-off-by: bpopovschi <zyqsempai@mail.ru>
Related to containerd/containerd#3709
Fixed Walk method signature to correspond new interface defined in containerd

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
https://github.com/containerd/containerd/pull/3709#discussion_r330922066

**Comment by fuweid** [comment]
ping @Zyqsempai 

https://github.com/containerd/containerd/pull/3709 has been merged, could you please to update your pr? thanks

**Comment by AkihiroSuda** [comment]
```
    --- FAIL: TestZFS/Walk (1.22s)
        testsuite.go:1087: [0] Unexpected result (size):
            Actual:
            	[]string{"a", "a-np", "a-np-wl", "a-wl", "v", "v-wl"}
            Expected:
            	[]string{"a", "a-np", "a-np-wl", "a-wl", "p", "p-wl", "v", "v-wl"}
        testsuite.go:1087: [3] Unexpected result (size):
            Actual:
            	[]string{}
            Expected:
            	[]string{"p", "p-wl"}
        testsuite.go:1087: [8] Unexpected result (size):
            Actual:
            	[]string{"a-np-wl", "a-wl", "v-wl"}
            Expected:
            	[]string{"a-np-wl", "a-wl", "p-wl", "v-wl"}
        helpers.go:67: drwx------       4096 /tmp/snapshot-suite-zfs-836927076
        helpers.go:67: drwxr-xr-x       4096 /tmp/snapshot-suite-zfs-836927076/root
        helpers.go:67: drwxr-xr-x       4096 /tmp/snapshot-suite-zfs-836927076/work
```

Seems regression?
cc @dmcgowan

**Comment by fuweid** [comment]
@Zyqsempai I will take a look this.

**Comment by Zyqsempai** [comment]
Any news here?

**Comment by dmcgowan** [comment]
> Seems regression?

Walk is a new test, so hard to tell if it is a regression. The issue may have existed previously and been unknown. Still investigating.

**Comment by dmcgowan** [comment]
I found the bug, I will open up a separate PR for it. The Commit function wasn't passing along the opts so the labels weren't getting set.

**Comment by dmcgowan** [comment]
I added the commit here since a separate PR would just fail without this PR anyway (since we don't have vendoring here)

**Pull request merged**
